import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
    {
      type: "link",
      label: "API Reference",
      href: "https://api.coderabbit.ai/api/swagger/"
    },
    {
      type: "link",
      label: "Blog",
      href: "https://blog.coderabbit.ai/blog",
    },
    {
      type: "link",
      label: "Discord",
      href: "https://discord.gg/GsXnASn26c",
    },
  ],
};

export default sidebars;
